version: '3'

services:
  web:
   container_name: "booking-react-front"
   image: booking-react
   volumes:
     - ./templates/link_config:/usr/share/nginx/html/link_conf_template
     - ./templates/nginx_config.template.conf:/tmp/nginx_config.template.conf
   ports:
   - "8080:80"
   environment:
   - BOOKING_EXTERNAL_LINK_URL=http://google.ru
   - BOOKING_EXTERNAL_LINK_DESCRIPTION=Приложение 2
   - SERVICE_API=http://1.1.1.1:8082/
   - SERVICE_API_EXTERNAL=http://1.1.1.1:8081
   - SERVICE_API_EXTERNAL_2=http://1.1.1.1:8083/
   - ESC=$$ #неизменять
   entrypoint: /bin/sh
   command: >
      -c "envsubst < /usr/share/nginx/html/link_conf_template > /usr/share/nginx/html/link_config.json 
      && envsubst < /tmp/nginx_config.template.conf > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"

